yarnPath: .yarn/releases/yarn-3.1.0.cjs

nodeLinker: node-modules

packageExtensions:
  "@vitejs/plugin-vue@*":
    peerDependencies:
      vue: ">=3.2.13"
  element-plus@*:
    dependencies:
      "@vue/shared": ">=3.2.13"
  vue-eslint-parser@*:
    peerDependencies:
      "@typescript-eslint/parser": "*"